---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ccj.
--- DateTime: 2024/7/8 20:59
--- 获取群聊里面的全部用户uid列表, 例如[1,2,3,4]， 然后判断是否在线, 假如在线的有1和4, 就返回2,表示这些人中有两个在线
--- 如果没有群聊key那就表示缓存失效了, 需要后端自己去查询群聊的全部uid
---

local roomId = tonumber(ARGV[1]) -- 房间号

local groupMemberKey = 'campus-chat:groupMember:roomId_' .. roomId
local onlineStatusKey = 'campus-chat:user:allUserOnlineStatus'

-- 检查群成员列表的key是否存在
local exists = redis.call('EXISTS', groupMemberKey)
if exists == 0 then
    -- 群成员的缓存失效了
    return cjson.encode(-1)
end

-- 获取群内所有成员的UID
local allGroupMembers = redis.call('ZRANGE', groupMemberKey, 0, -1)

local onlineCount = 0

-- 遍历成员UID，检查每个成员的在线状态
for _, memberUid in ipairs(allGroupMembers) do
    local status = redis.call('GETBIT', onlineStatusKey, tonumber(memberUid))
    if status == 1 then
        onlineCount = onlineCount + 1
    end
end

return cjson.encode(onlineCount)
