---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ccj.
--- DateTime: 2024/7/8 19:38
--- 更新用户的在线状态
---

--- KEYS[1]：用户ID
--- ARGV[1]：新状态（例如 "1" 表示在线，"0" 表示离线）

local uid = tonumber(ARGV[1])
local status = tonumber(ARGV[2])

local key = "campus-chat:user:allUserOnlineStatus"

--SETBIT key offset value[0或1]  如：SETBIT b1 0 1
redis.call('SETBIT', key, uid, status)
