---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ccj.
--- DateTime: 2024/7/24 21:49
---

local key = KEYS[1]
local ttl = tonumber(ARGV[1])

if redis.call('exists', key) == 0 then
    redis.call('setnx', key, 1)
    redis.call('expire', key, ttl)
    return 1
else
    return tonumber(redis.call('INCR', key))
end
